#define COLOR_VENDORS      BOLD AQUA
#define COLOR_COMMAND      CORNSILK1
#define COLOR_COND         SILVER
#define COLOR_KEYWORD      MAROON
#define COLOR_PROTOCOL     OLIVE
#define COLOR_STRING       YELLOW
#define COLOR_INTERFACE    BLUE
#define COLOR_ACTION       UNDERLINE FUCHSIA
#define COLOR_VAR          TEAL
#define COLOR_IPV4_NET     RED
#define COLOR_IPV4_SUB     YELLOW3
#define COLOR_IPV4_WILD    LIME
#define COLOR_COMMENT      STEELBLUE
#define COLOR_IPV6         SPRINGGREEN
#define COLOR_EMPHASIS     ORANGE
#define COLOR_POSITIVE     DARKORANGE
#define COLOR_URL          UNDERLINE STEELBLUE1
#define COLOR_SLASH        DEEPPINK
// ToDo
//#define COLOR_CONFIGURE
//#define COLOR_FUNCTION
